FROM node:24.12.0-alpine AS web-build
WORKDIR /data/
COPY ./web ./web
WORKDIR /data/web
RUN cp ./public/config.json.example ./public/config.json && cp ./nginx.conf.example ./nginx.conf
RUN npm install
RUN npm run build

FROM nginx:alpine AS web
WORKDIR /data/
COPY --from=web-build /data/web/dist ./web/
COPY --from=web-build /data/web/nginx.conf /etc/nginx/nginx.conf
WORKDIR /data/web

EXPOSE 80
# CMD [ "sh", "/data/passwordserver/start.sh" ]
